version: '2'
services:
    flashcards-app:
        image: flashcards
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://flashcards-postgresql:5432/flashcards
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    flashcards-postgresql:
        extends:
            file: postgresql.yml
            service: flashcards-postgresql
